# Generated by Django 4.0.1 on 2022-01-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tags', models.CharField(choices=[('v', 'Volcanic Eruption'), ('e', 'Earthquake')], max_length=3)),
                ('description', models.TextField()),
            ],
        ),
    ]
