# Generated by Django 4.0.1 on 2022-01-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecard',
            name='placedBased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='knowledgecard',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
