# Generated by Django 4.0.1 on 2022-01-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_knowledgecard_placedbased_alter_knowledgecard_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgecard',
            old_name='placedBased',
            new_name='placed_based',
        ),
    ]
