# Generated by Django 4.0.1 on 2022-01-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_placedbased_knowledgecard_placed_based'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.CharField(max_length=500)),
                ('description', models.TextField(help_text='A brief explanation of what this video presents')),
                ('video_authors', models.TextField(help_text='List of authors responsible for the video. Separate each author with a comma')),
                ('reviewers', models.TextField(help_text='List of reviewers for this video. Separate each reviewer with a comma')),
                ('audience_level', models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced')], max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='knowledgecard',
            old_name='placed_based',
            new_name='place_based',
        ),
    ]
