# Generated by Django 4.0.1 on 2022-01-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_knowledgecard_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgecard',
            name='tags',
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='topic',
            field=models.CharField(choices=[('vol', 'Volcanic Eruption'), ('eq', 'Earthquake'), ('pt', 'Plate Tectonics'), ('min', 'Minerals'), ('sg', 'Structural Geology'), ('met', 'Metamorphism'), ('mag', 'Magmatism'), ('hyd', 'Hydrology'), ('env', 'Environmental Geology'), ('sed', 'Sedimentology'), ('his', 'Historical Geology'), ('pal', 'Paleomagnetism'), ('hum', 'Human Activity'), ('nat', 'Natural Hazards')], default='Volcanic Eruption', help_text='Which knowledge base topic does this card fall under?', max_length=3),
        ),
    ]
